SET(DEBUG_LOG OFF CACHE BOOL "Enable debug logging")
if(DEBUG_LOG)
    message("✅ DEBUG LOG")
    add_compile_definitions(DEBUG_LOG=1)
else()
    message("❌ DEBUG LOG")
endif(DEBUG_LOG)

SET(USE_COUNTER_GC_EVENTS ON CACHE BOOL "Use counter JVMTI GC events")
if(USE_COUNTER_GC_EVENTS)
    message("✅ USE COUNTER GC EVENTS")
    add_compile_definitions(USE_COUNTER_GC_EVENTS=1)
else()
    message("❌ USE COUNTER GC EVENTS")
endif(USE_COUNTER_GC_EVENTS)

add_compile_options(-O3 -Wall -Werror)
add_subdirectory(counter)
add_subdirectory(simulator)
